[samples]
1 = {name = "Kick1", file="samples/wee_noise_maker/raw_44100/kick1-1.raw"}
2 = {name = "Kick2", file="samples/wee_noise_maker/raw_44100/kick1-2.raw"}
3 = {name = "Kick3", file="samples/wee_noise_maker/raw_44100/kick1-3.raw"}
4 = {name = "Kick4", file="samples/wee_noise_maker/raw_44100/kick1-4.raw"}
5 = {name = "Kick5", file="samples/wee_noise_maker/raw_44100/kick1-5.raw"}
6 = {name = "Kick6", file="samples/wee_noise_maker/raw_44100/kick1-6.raw"}
7 = {name = "Kick7", file="samples/wee_noise_maker/raw_44100/kick1-7.raw"}
8 = {name = "Kick8", file="samples/wee_noise_maker/raw_44100/kick1-8.raw"}
9 = {name = "Kick9", file="samples/wee_noise_maker/raw_44100/kick1-9.raw"}
10 = {name = "Kick10", file="samples/wee_noise_maker/raw_44100/kick1-10.raw"}

11 = {name = "Snare1", file="samples/wee_noise_maker/raw_44100/snare1-1.raw"}
12 = {name = "Snare2", file="samples/wee_noise_maker/raw_44100/snare1-2.raw"}
13 = {name = "Snare3", file="samples/wee_noise_maker/raw_44100/snare1-3.raw"}
14 = {name = "Snare4", file="samples/wee_noise_maker/raw_44100/snare1-4.raw"}
15 = {name = "Snare5", file="samples/wee_noise_maker/raw_44100/snare1-5.raw"}

16 = {name = "ClosedHH1", file="samples/wee_noise_maker/raw_44100/closedhh1-1.raw"}
17 = {name = "ClosedHH2", file="samples/wee_noise_maker/raw_44100/closedhh1-2.raw"}
18 = {name = "ClosedHH3", file="samples/wee_noise_maker/raw_44100/closedhh1-3.raw"}
19 = {name = "ClosedHH4", file="samples/wee_noise_maker/raw_44100/closedhh1-4.raw"}
20 = {name = "ClosedHH5", file="samples/wee_noise_maker/raw_44100/closedhh1-5.raw"}

21 = {name = "OpenHH1", file="samples/wee_noise_maker/raw_44100/openhh1-1.raw"}
22 = {name = "OpenHH2", file="samples/wee_noise_maker/raw_44100/openhh1-2.raw"}
23 = {name = "OpenHH3", file="samples/wee_noise_maker/raw_44100/openhh1-3.raw"}
24 = {name = "OpenHH4", file="samples/wee_noise_maker/raw_44100/openhh1-4.raw"}
25 = {name = "OpenHH5", file="samples/wee_noise_maker/raw_44100/openhh1-5.raw"}

26 = {name = "Tom1", file="samples/SVModular/tomi/raw_44100/05.raw"}
27 = {name = "Tom2", file="samples/SVModular/tomi/raw_44100/06.raw"}
28 = {name = "Tom3", file="samples/SVModular/tomi/raw_44100/07.raw"}
29 = {name = "Tom4", file="samples/SVModular/tomi/raw_44100/08.raw"}
30 = {name = "Tom5", file="samples/SVModular/tomi/raw_44100/09.raw"}
31 = {name = "Tom6", file="samples/SVModular/tomi/raw_44100/11.raw"}
32 = {name = "Tom7", file="samples/SVModular/tomi/raw_44100/14.raw"}

33 = {name = "Ride1", file="samples/avl_drumkits/AVL-BlackPearl-5-1.1/raw_44100/51-SabianAAX20Ride-1.raw"}
34 = {name = "BongoHi1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoHi-Soft.raw"}
35 = {name = "BongoHi2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoHi-Med.raw"}
36 = {name = "BongoLo1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoLo-Soft.raw"}
37 = {name = "BongoLo2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/BongoLo-Med.raw"}
38 = {name = "CajonSlaps1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonSlaps-Soft.raw"}
39 = {name = "CajonSlaps2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonSlaps-Med.raw"}
40 = {name = "CajonThumps1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonThumps-Soft.raw"}
41 = {name = "CajonThumps2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/CajonThumps-Med.raw"}
42 = {name = "Clave1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Clave-Soft.raw"}
43 = {name = "Clave2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Clave-Med.raw"}
44 = {name = "FingerSnap1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Fingersnap-Soft.raw"}
45 = {name = "FingerSnap2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Fingersnap-Med.raw"}
46 = {name = "HandClap1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/HandClap-Soft.raw"}
47 = {name = "HandClap2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/HandClap-Hard.raw"}
48 = {name = "Maraca1", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Maraca-Soft.raw"}
49 = {name = "Maraca2", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Maraca-Med.raw"}
50 = {name = "Tambourine", file="samples/avl_drumkits/Gimme-A-Hand-1.0/raw_44100/Tambourine-Med.raw"}
